### PR TITLE
Added support for the institutions API calls and fixed some other things

### PR DESCRIPTION
**Pull request by einsteinx2**

### CODE REVIEW

**Comment by einsteinx2** [comment]
Today I did a bunch of work on error handling, which it looks like is now grouped into this pull request.

Previously many errors were being swallowed by Plaidster (anything that hit the catch block). This would not only hide the error from the application, but also fail to call the handler which breaks flow control when nesting API calls in completion handlers.

I've improved the PlaidError and PlaidsterError ErrorTypes to allow them to be easily converted to NSErrors. Then I improved the PlaidApi functions to convert exceptions to NSErrors and call their handlers on failures. Also I consolidated the JSONError and PlaidError types as well as made all error types public so they can be used in the enclosing application (for example to check error codes).

Eventually I'll add PlaidErrors for more Plaid error codes, but this lays the foundation for proper error handling.

**Comment by istx25** [comment]
Sweet. Would you mind moving these over to [istx25/plaid-swift](http://github.com/istx25/plaid-swift)? I've reached out to Plaid about making that binding the new community one. If you're interested, I could talk in more detail about why I'm working on that one now. Tests first and also has a bit of a different kind of code design.

**Comment by istx25** [comment]
I love what you're doing with the error handling so that especially could be moved over to the new project.

**Comment by einsteinx2** [comment]
Sure np. I think at this point we may be too far along in our application to switch libraries, but I don't mind taking a look to see if I can add this code and get a feel for the new library.

I'm interested in hearing more about why you started over, aside from the tests which is great.

**Comment by istx25** [comment]
If you want I can transfer the Plaidster repository to you. I was planning on just removing it once the same amount of functionality was rebuilt over in plaid-swift. I primarily changed rewrote it because I wanted a fresh start and to write a library that was also similar to Plaid's API that also adhered to the Swift language guidelines/styles. I also wanted to try out a different style for designing the project. I was reading through the code for the other language libraries and a lot on how Swift frameworks should/can be built rather than just throwing it all together and hoping it worked. 💃

**Comment by istx25** [comment]
I'll merge this in though. @einsteinx2

**Comment by einsteinx2** [comment]
I'd be happy to take over the repo. Not sure how the transfer process works, but let me know.

**Pull request merged**
